name: 'Zendesk Actions'
description: 'Greet someone and record the time'
inputs:
  token:  # id of input
    description: 'Zendesk API Token'
    required: true
    default: ''
  org:
    description: 'Github Organization'
    required: true
    default: 'Realtimeinfotech'
  repo:
    description: 'Github Repository'
    required: true
    default: 'realtime'
  zd_token:
    description: 'Zendesk API Token'
    required: true
    default: ''
  zd_base_url:
    description: 'Zendesk Base URL'
    required: true
    default: ''
  zd_case_status_id:
    description: 'Zendesk Case Status Id'
    required: true
    default: ''
  rt_api_token:
    description: 'Realtime API token'
    required: true
    default: ''
outputs:
  action_result: # id of output
    description: 'Result of the action'
runs:
  using: 'node12'
  main: 'dist/index.js'

